version: '3.8'

services:
  web:
    restart: on-failure
    build: .
    ports:
      - "5000:5000"
    networks:
      - mainnetwork
    command: python main.py

networks:
  mainnetwork:
    external: true
